---
title: "Race Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)


````


```{r}




setwd("~/Projects/F1/Data")



circuits <- read_csv("circuits.csv")

constures <- read_csv("constructor_results.csv")

construcst <- read_csv("constructor_standings.csv")

constructors <- read_csv("constructors.csv")

dristan <- read_csv("driver_standings.csv")


drivers <- read_csv("drivers.csv")


laptimes <- read_csv("lap_times.csv")


pits <- read_csv("pit_stops.csv")

qual = read_csv("qualifying.csv")

races <- read_csv("races.csv")

results <- read_csv("results.csv")

seasons <- read_csv("seasons.csv")

status <- read_csv("status.csv")



tyreuse <- read_csv("F1 Tyre Usage.csv")



```

```{r}


lapcount <- results %>% group_by(raceId) %>%
                            slice_max(laps) %>%
                              distinct(laps, .keep_all = T) %>%
                                select(raceId, laps)


colnames(lapcount)[2] <- "tlap"


```


```{r}



lando <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(name == "Styrian Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("HAM")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(year) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 74) %>%
                                                select(lap, seconds, year, stint)


ggplot(lando, aes(x = lap, y = seconds, col = as.factor(year))) + 
                                        geom_point() +  geom_smooth(method = "lm", se = F) +
                                          facet_wrap(~stint, scales = "free_x")



```

```{R}



lando2 <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(name == "Austrian Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("HAM")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(year) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 74) %>%
                                              select(lap, seconds, year, stint)


ggplot(lando2, aes(x = lap, y = seconds, col = as.factor(year))) + 
                                        geom_point() +  geom_smooth(method = "lm", se = F) +
                                          facet_wrap(~stint, scales = "free_x")









```
```{r}


colnames(lando)[2] <- "Styria_lt"

colnames(lando2)[2] <- "Austria_lt" 



lan_com <- lando %>% left_join(lando2, by = "lap") %>%
                        select(lap, Styria_lt, Austria_lt) %>%
                            pivot_longer(cols = 2:3, names_to = "race", values_to = "lt")



ggplot(lan_com, aes(x = lap, y = lt, col = race)) + geom_point()



```

```{r}




lan_com2 <- lan_com %>% mutate(fuelds = (71-(lap+1)) * 0.06) %>%
                            mutate(ltfuel = lt-fuelds)



ggplot(lan_com2, aes(x = lap, y = ltfuel, col = race)) + 
                                        geom_point()  

````

```{r}




land3_2 <- lando2 %>%    filter(lap > 4) %>%
                        mutate(fuelds = (71-(lap+1)) * 0.06) %>%
                            mutate(ltfuel = Austria_lt-fuelds) %>%
                         group_by(stint) %>%
                          slice(which.min(lap))

colnames(land3_2)[2] <- "minlt"
colnames(land3_2)[6] <- "minflt"



land3_3 <- lando2 %>% left_join(land3_2, by = c("stint")) %>%
                          mutate(fuelds = (71-(lap.x+1)) * 0.06) %>%
                            mutate(ltfuel2 = Austria_lt-fuelds) %>%
                              mutate(delta = ltfuel2-minflt)



land_cum <- land3_3 %>% group_by(stint) %>%
                            mutate(closs = cumsum(delta), stinl = 1:n())


ggplot(land_cum, aes(x = stinl, y = closs, col = as.factor(stint))) + geom_point(se = F)

````

```{r}


ggplot(land3_3, aes(x = lap.x, y = ltfuel2)) + geom_point()
 


```


```{R}


land2 <- lando %>% mutate(laple = 70-(lap-1)) %>%
                    mutate(fuelcorr = seconds - (laple * 0.06)) %>%
                      group_by(stint) %>%
                        mutate(stintl = 1:n()) %>%
                         




ggplot(land2, aes(x = stintl, y = fuelcorr, col = as.factor(stint))) + 
                                                        geom_point() + 
                                                      geom_smooth(method = "lm", se =F)




```



```{r}




verham <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                          
                            filter(name == "Styrian Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("NOR", "SAI")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 105) %>%
                                                filter(stint < 4)


ggplot(verham, aes(x = lap, y = seconds, col = as.factor(code))) + 
                                        geom_point() +  geom_smooth( se = F) +
                                          facet_wrap(~stint, scales = "free_x")









````


```{r}


verham_sm <- verham %>% group_by(code, stint) %>% 
                         slice_min(seconds) %>%
                            select(code, stint, seconds)

colnames(verham_sm)[3] <- "mint"


verham_mx <- verham %>% group_by(code, stint) %>% 
                         slice_max(seconds) %>%
                            select(code, stint, seconds)

colnames(verham_mx)[3] <- "maxt"



verham_sl <- verham %>% group_by(code, stint) %>% 
                          summarise(n = n())


varhamcom <- verham_sm %>% left_join(verham_mx, by = c("code", "stint")) %>%
                            left_join(verham_sl, by = c("code", "stint")) %>%
                              mutate(stintloss = (maxt - mint)/n)


```

```{r}



verham2 <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            left_join(lapcount, by = "raceId") %>%
                            filter(name == "French Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("HAM", "VER")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                     mutate(fueladj = (seconds-(((tlap-lap)+1) * 0.06))) %>%
                                      group_by(code) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 100) %>%
                                                filter(stint < 4)
                                                    





ggplot(verham2, aes(x = lap, y = fueladj, col = as.factor(code))) + 
                                        geom_point() +  geom_smooth(method = "lm", se = F) +
                                          facet_wrap(~stint, scales = "free_x")







```

```{r}



verham2_sm <- verham2 %>% group_by(code, stint) %>% 
                         slice_min(fueladj) %>%
                            select(code, stint, fueladj)

colnames(verham2_sm)[3] <- "mint"


verham2_mx <- verham2 %>% group_by(code, stint) %>% 
                         slice_max(fueladj) %>%
                            select(code, stint, fueladj)

colnames(verham2_mx)[3] <- "maxt"



verham2_sl <- verham2 %>% group_by(code, stint) %>% 
                          summarise(n = n())


varhamcom2 <- verham2_sm %>% left_join(verham2_mx, by = c("code", "stint")) %>%
                            left_join(verham2_sl, by = c("code", "stint")) %>%
                              mutate(stintloss = (maxt - mint)/n)




````


```{r}


pits31 <- pits %>% filter(raceId == 1031)
 

```


```{r}




ham <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(raceId == 1031) %>%
                                filter(code %in% c("ALB")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                         
                                                  ungroup() %>%
                                                    group_by(stint) %>%
                                                        mutate(stintlp = 1:n()) 




ggplot(ham, aes(x = lap, y = seconds, col = as.factor(stint))) + geom_point()



`````

```{R}


HAM2 <- ham %>% filter(stintlp < 17) %>%
                      group_by(stint) %>%
                        summarise(meanl = mean(seconds))



```


```{r}


ham3 <- ham %>% ungroup() %>%
          mutate(fueladj = seconds - (lap *0.07)) 


ggplot(ham3, aes(x = lap, y = fueladj)) + geom_point()
```

```{r}




BOT <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(name == "Bahrain Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("BOT")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                         
                                                  ungroup() %>%
                                                    group_by(stint) %>%
                                                        mutate(stintlp = 1:n()) %>%
                                                        mutate(fueladj = 97.0661-(lap*0.0873))








ggplot(BOT, aes(x = lap, y = fueladj)) + geom_point()




````

```{r}


qualbest <- qual %>% pivot_longer(cols = 7:9, names_to = "qaul", values_to = "times") %>%
                                    filter(qaul == "q3") %>%
                                      separate(times, into = c("m", "s","ms"), sep = ":")


qualbest$m <- as.numeric(as.character(qualbest$m))

qualbest$s <- as.numeric(as.character(qualbest$s))



qualbest2 <- qualbest %>% mutate(qualt = m * 60 + s) %>%
                      left_join(races, by = "raceId") %>%
                            left_join(circuits, by = "circuitId") %>%
                                group_by(circuitId) %>%
                                  slice_min(qualt)



                              




```
```{r}



lapfil_test <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                              filter(year > 2010) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code, raceId) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                            left_join(qualbest2, by = "circuitId") %>%
                                              mutate(delta = seconds/qualt-1) %>%
                                                filter(seconds < 200)



ggplot(lapfil_test, aes(x = delta)) + geom_histogram(binwidth = 0.01)









```

```{r}


medlap <- laptimes %>%  mutate(seconds = milliseconds / 1000) %>%
                           group_by(raceId) %>%
                              summarise(ml = median(seconds))


medlap2 <- laptimes %>% left_join(medlap, by = "raceId") %>%
                                     mutate(seconds = milliseconds / 1000) %>%
                                        mutate(delta = seconds - ml) %>%
                                          filter(raceId > 1029) %>%
                                              filter(delta <100)


ggplot(medlap2, aes(x = delta)) + geom_histogram(binwidth = 1)


```




```{r}




tyre_use2 <- tyreuse %>% pivot_longer(cols = 4:14, names_to = "na", values_to = "tyre") %>%
                                  separate(na, into = c("nar", "stint"), "_")



tyre_use2$stint <- as.numeric(as.character(tyre_use2$stint))







```



```{r}




all_stints <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                              filter(year > 2019) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code, raceId) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                            left_join(qualbest2, by = "circuitId") %>% 
                                              
                                              mutate(delta = seconds/qualt-1) %>%
                                                filter(delta < 0.5) %>%
                                                  ungroup() %>%
                                                    group_by(stint) %>%
                                                        mutate(stintlp = 1:n()) %>%
                                                          group_by(code, year.x, round.x, stint) %>%
                                                            summarise(medl = median(seconds), n = n()) 

colnames(all_stints)[1] <- "Driver"
colnames(all_stints)[2] <- "Season"
colnames(all_stints)[3] <- "Race"



```

```{r}




all_stints2 <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                              filter(year > 2019) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(code, raceId) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                            left_join(qualbest2, by = "circuitId") %>% 
                                              
                                              mutate(delta = seconds/qualt-1) %>%
                                                filter(delta < 0.5) %>%
                                                  ungroup() %>%
                                                    group_by(stint,raceId.x, code) %>%
                                                        mutate(stintlp = 1:n())  %>%
                                                              filter(stintlp == 4) %>%
                                                              mutate(minl = min(lap)) %>%
                                                                ungroup() %>%
                                                                  select(code, year.x, round.x, stint, seconds, minl)

colnames(all_stints2)[1] <- "Driver"
colnames(all_stints2)[2] <- "Season"
colnames(all_stints2)[3] <- "Race"






```



```{r}


ggplot(all_stints2, aes(x = stintlp)) + geom_histogram()









```

```{r}

all_stints_t <- all_stints %>% left_join(tyre_use2, by = c("Driver", "Season", "Race", "stint")) %>%
                        left_join(all_stints2, by = c("Driver", "Season", "Race", "stint")) %>%
                                select(Driver, Season, Race, stint, tyre) %>%
                                  pivot_wider(names_from = stint, values_from = tyre) %>%
                                    mutate(stint_1 = if_else(`1` == `2`, 1, 
                                                             if_else(`1` == `3`, 1, 
                                                              if_else(`1` == `4`, 1, 
                                                               if_else(`1` == `5`, 1, 0))))) %>%
                                    mutate(stint_2 = if_else(`2` == `1`, 1, 
                                                             if_else(`2` == `3`, 1, 
                                                              if_else(`2` == `4`, 1, 
                                                               if_else(`2` == `5`, 1, 0))))) %>%
                                      mutate(stint_3 = if_else(`3` == `1`, 1, 
                                                             if_else(`3` == `2`, 1, 
                                                              if_else(`3` == `4`, 1, 
                                                               if_else(`3` == `5`, 1, 0))))) %>%
                                        mutate(stint_4 = if_else(`4` == `1`, 1, 
                                                             if_else(`4` == `2`, 1, 
                                                              if_else(`4` == `3`, 1, 
                                                               if_else(`4` == `5`, 1, 0))))) %>%
                                          mutate(stint_5 = if_else(`5` == `1`, 1, 
                                                             if_else(`5` == `2`, 1, 
                                                              if_else(`5` == `4`, 1, 
                                                               if_else(`5` == `3`, 1, 0))))) %>%
                                            select(-`1`, -`2`, -`3`, -`4`,-`5`,-`6`,-`7`) %>%
                               pivot_longer(cols = 4:8, names_to = "st", values_to = "match") %>%
                                          separate(col = st, into = c("st", "stint"), sep = "_") %>%
                                                  select(-st)


all_stints_t$stint <- as.numeric(as.character(all_stints_t$stint))

````




```{r}


all_stints_3 <- all_stints %>% left_join(tyre_use2, by = c("Driver", "Season", "Race", "stint")) %>%
                        left_join(all_stints2, by = c("Driver", "Season", "Race", "stint")) %>%
                                left_join(all_stints_t,by = c("Driver", "Season", "Race", "stint") ) %>%
                                      filter(match == 1)



lapdelta <-  all_stints_3 %>% select(Driver, Season, Race, stint, minl) %>%
                                   group_by(Driver, Season, Race) %>%
                                      mutate(stin = 1:n()) %>%
                                        filter(stin < 3) %>%
                                          select(-stint) %>%
                                    pivot_wider(names_from = stin, values_from = minl) %>%
                                          mutate(dell = `2`-`1`) %>%
                                            select(-`1`, -`2`)

```




```{r}

all_stints_4 <- all_stints_3 %>% select(Driver, Season, Race, stint, medl) %>%
                            group_by(Driver, Season, Race) %>%
                                      mutate(stin = 1:n()) %>%
                                        filter(stin < 3) %>%
                                          select(-stint)  %>%
                                              pivot_wider(names_from = stin, values_from = medl) %>%
                                        left_join(lapdelta, by = c("Driver", "Season", "Race")) %>%
                                            mutate(fuelr = (`1`-`2`)/dell) %>%
                                                filter(!is.na(fuelr)) %>%
                                                  filter(fuelr < 1)



ggplot(all_stints_4, aes(x = fuelr)) + geom_histogram(binwidth = 0.01)




```





```{r}



ggplot(all_stints_4, aes(x = Race, y = fuelr)) + geom_point() +
                                                  geom_smooth(method = "lm")





```



```{r}



all_stints_f <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                               left_join(lapcount, by = "raceId") %>%
                              filter(year > 2019) %>%
                                  group_by(raceId, code) %>%
                                  fill(stop, .direction = c("down")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>% 
                                     mutate(fueladj = (seconds-(((tlap-lap)+1) * 0.06))) %>%
                                     
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                              ungroup() %>%
                                            left_join(medlap, by = "raceId") %>% 
                                              filter(is.na(time)) %>%
                                              mutate(delta = seconds-ml) %>%
                                                   filter(delta < 5) %>%
                                                    group_by(stint) %>%
                                                        mutate(stintlp = 1:n()) %>%
                                                  ungroup() %>%
                                                    group_by(stint,raceId, code) %>%
                                                        mutate(stintlp = 1:n())  %>%
                                                          select(raceId, driverId,lap,year, round, name, code,stop, tlap,seconds, fueladj,stint)
    




```


```{r}

test <- all_stints_f %>% filter(code == "NOR") %>%
                        filter(raceId == 1047)


````

```{R}


ggplot(test, aes(x = lap, y = fueladj)) + geom_point()

````


```{r}


bot_test <- all_stints_f %>%   select(raceId, driverId,lap,year, round, name, code,stop, tlap,seconds, fueladj,stint) %>%
                        filter(code == "HAM") %>%
                        filter(raceId == 1053)
    



```


```{r}


alls_min <- all_stints_f %>% group_by(code, stint, raceId) %>% 
                         slice_min(fueladj) %>%
                            select(code, stint, raceId, fueladj)

colnames(alls_min)[4] <- "mint"


alls_mx <- all_stints_f %>% group_by(code, stint, raceId) %>% 
                         slice_max(fueladj) %>%
                            select(code, stint, raceId, fueladj)

colnames(alls_mx)[4] <- "maxt"



alls2_sl <- all_stints_f %>% group_by(code, stint, raceId) %>% 
                          summarise(n = n())


all_stint_loss <- alls_min %>% left_join(alls_mx, by = c("code", "stint", "raceId")) %>%
                            left_join(alls2_sl, by = c("code", "stint", "raceId")) %>%
                              mutate(stintloss = (maxt - mint)/n) %>%
                                filter(stintloss < 1) %>%
                                    filter(n > 1)

ggplot(all_stint_loss, aes(x = stintloss)) + geom_histogram(binwidth = 0.01)



````




```{r}




ggplot(all_stint_loss, aes(x = code, y = stintloss)) + geom_boxplot() +
                                                    coord_flip()




````





```{r}




ggplot(all_stint_loss, aes(x = n, y = stintloss)) + geom_point() + geom_smooth()




```

```{r}


safe1 <- laptimes %>% left_join(races, by = "raceId") %>%
                         left_join(qualbest2, by = "circuitId") %>%
                      select(raceId.x, circuitId, lap, position.x, milliseconds, qualt)  %>%
                        filter(position.x == 1) %>%
                            mutate(delta = (milliseconds/1000)/qualt) %>%
                             mutate(lapco = if_else(delta > 1.25, "safety", "norm"))


colnames(safe1)[1] <- "raceId"

```



```{r}


drivet <- results %>% left_join(constructors, by = "constructorId") %>%
                            left_join(races, by = "raceId") %>%
                                filter(year == 2021) %>%
                                  filter(raceId == 1059) %>%
                                      select(driverId, constructorId)



```


```{r}


first <- laptimes %>% filter(position == 1) %>%
                      select(raceId, lap, milliseconds) 

colnames(first)[3] <- "fast"


allrace <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                              filter(year == 2021) %>%
                                left_join(safe1, by = c("raceId", "lap")) %>%
                                  left_join(first, by = c("raceId", "lap")) %>%
                                    filter(lapco == "norm") %>%
                                      mutate(diff = milliseconds.x/fast-1) %>%
                                        left_join(drivet, by = "driverId") %>% 
                                        group_by(constructorId) %>%
                                          summarise(meandel = mean(diff)) %>%
                                            left_join(constructors, by = "constructorId")










````


```{r}


maxlap <- laptimes %>% group_by(raceId) %>%
                           slice( which.max(lap)) %>%
                              select(raceId, lap)

colnames(maxlap)[2] <- "totlap"


allrace <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                              left_join(maxlap, by = "raceId") %>%
                              filter(year == 2021) %>%
                                left_join(safe1, by = c("raceId", "lap")) %>%
                                  left_join(first, by = c("raceId", "lap")) %>%
                                    filter(lapco == "norm") %>%
                  mutate(diff = milliseconds.x/fast-1, perrace = round(lap/totlap*100),0) %>%
                                      
                                        left_join(drivet, by = "driverId") %>% 
                                        group_by(constructorId, perrace) %>%
                                          summarise(meandel = mean(diff)) %>%
                                            left_join(constructors, by = "constructorId")


````



```{r}




ggplot(allrace, aes(x = perrace, y = meandel, col = name)) + geom_point()




```



```{r}


mcl <- allrace %>% filter(name == "McLaren")




ggplot(mcl, aes(x = perrace, y = meandel, col = name)) + geom_point()







```

```{r}





lapcount <- results %>% group_by(raceId) %>%
                            slice_max(laps) %>%
                              distinct(laps, .keep_all = T) %>%
                                select(raceId, laps)


colnames(lapcount)[2] <- "tlap"


```


```{r}



lando_gb <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(name == "British Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("HAM")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(year) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 100) %>%
                                                select(lap, seconds, year, stint)


ggplot(lando_gb, aes(x = lap, y = seconds, col = as.factor(year))) + 
                                        geom_point() +  geom_smooth(method = "lm", se = F) +
                                          facet_wrap(~stint, scales = "free_x")



```

```{R}



lando2 <- laptimes %>% left_join(races, by = "raceId") %>%
                                left_join(drivers, by = "driverId") %>%
                        left_join(pits, by = c("raceId", "lap", "driverId")) %>%
                            filter(name == "Austrian Grand Prix") %>%
                              filter(year > 2020) %>%
                                filter(code %in% c("HAM")) %>%
                                  mutate(seconds = milliseconds.x / 1000) %>%
                                      group_by(year) %>%
                                      fill(stop) %>%
                                      mutate(stint = if_else(is.na(stop),1, 1 + stop)) %>%
                                      mutate(lugdur = lag(duration)) %>%
                                        mutate(stopfl = if_else(!is.na(duration),1 ,
                                                          if_else(!is.na(lugdur), 1, 2))) %>%
                                          filter(stopfl == 2) %>%
                                              filter(seconds < 74) %>%
                                              select(lap, seconds, year, stint)


ggplot(lando2, aes(x = lap, y = seconds, col = as.factor(year))) + 
                                        geom_point() +  geom_smooth(method = "lm", se = F) +
                                          facet_wrap(~stint, scales = "free_x")









```


```{r}


colnames(lando)[2] <- "Styria_lt"

colnames(lando2)[2] <- "Austria_lt" 



lan_com <- lando %>% left_join(lando2, by = "lap") %>%
                        select(lap, Styria_lt, Austria_lt) %>%
                            pivot_longer(cols = 2:3, names_to = "race", values_to = "lt")



ggplot(lan_com, aes(x = lap, y = lt, col = race)) + geom_point()



```

```{r}




lan_com2 <- lan_com %>% mutate(fuelds = (71-(lap+1)) * 0.06) %>%
                            mutate(ltfuel = lt-fuelds)



ggplot(lan_com2, aes(x = lap, y = ltfuel, col = race)) + 
                                        geom_point()  

````

```{r}




land3_2 <- lando_gb %>%    filter(lap > 4) %>%
                        mutate(fuelds = (52-(lap+1)) * 0.06) %>%
                            mutate(ltfuel = seconds-fuelds) %>%
                         group_by(stint) %>%
                          slice(which.min(lap))

colnames(land3_2)[2] <- "minlt"
colnames(land3_2)[6] <- "minflt"


land3_3 <- lando_gb %>% left_join(land3_2, by = c("stint")) %>%
                          mutate(fuelds = (52-(lap.x+1)) * 0.06) %>%
                            mutate(ltfuel2 = seconds-fuelds) %>%
                              mutate(delta = ltfuel2-minflt)



land_cum <- land3_3 %>% group_by(stint) %>%
                            mutate(closs = cumsum(delta), stinl = 1:n())


ggplot(land_cum, aes(x = stinl, y = closs, col = as.factor(stint))) + geom_point(se = F)

````







```


