---
title: "F1 Drivers Rated"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(tidyverse)


library(readxl)

library(tidymodels)

```


#### Data

```{r}


setwd("~/Projects/F1/Data")



circuits <- read_csv("circuits.csv")

constures <- read_csv("constructor_results.csv")

construcst <- read_csv("constructor_standings.csv")

constructors <- read_csv("constructors.csv")

dristan <- read_csv("driver_standings.csv")


drivers <- read_csv("drivers.csv")


laptimes <- read_csv("lap_times.csv")


pits <- read_csv("pit_stops.csv")

qual = read_csv("qualifying.csv")

races <- read_csv("races.csv")

results <- read_csv("results.csv")

seasons <- read_csv("seasons.csv")

status <- read_csv("status.csv")

factor <- read_xlsx("facetor.xlsx")

````



```{r}

all_data <- results %>% left_join(races, by = "raceId") %>%
                            left_join(constructors, by = "constructorId") %>%
                                left_join(drivers, by = "driverId") %>%
                                      left_join(status, by = "statusId")  %>%
                                      left_join(circuits, by = "circuitId")


#%>%
 ##                                     
   #                                     left_join(factor, by = c("Gridtot", "grid")) 

#all_data$position <- as.numeric(as.character(all_data$position))





```


```{r}

grid <- all_data %>% 
                            group_by(raceId, date) %>%  
                              summarise(Gridtot = n()) %>%
                                ungroup() %>%
                                arrange(date) %>%
                                  mutate(raceno = 1:n())


ggplot(grid, aes(x = raceno, y = Gridtot)) + 
                                    geom_line(col = "#32a852") + 
                          labs(x = "Race No", y = "Grid Size", title = "F1 Grid Size Through Time") + 
                                theme(panel.background = element_blank())

```

```{r}

all_data2 <- results %>% left_join(races, by = "raceId") %>%
                            left_join(constructors, by = "constructorId") %>%
                                left_join(drivers, by = "driverId") %>%
                                      left_join(status, by = "statusId") %>% 
                                       left_join(grid, by = "raceId") %>%
                                         left_join(factor, by = c("Gridtot", "grid")) 


all_data2$position <- as.numeric(as.character(all_data2$position))


```




```{r}


retire <- all_data2 %>% mutate(ret = if_else(positionText == "R", 1, 0 )) %>%
                            group_by(year) %>%
                              summarise(tot = n(), ret2 = sum(ret, na.rm = T)) %>%
                                mutate(per = ret2/tot)


ggplot(retire, aes(x = year, y = per)) + geom_col()



````





```{r}


retire_pos <- all_data2 %>% filter(grid > 0) %>%
                              filter(Gridtot == 20) %>%
                           mutate(ret = if_else(positionText == "R", 1, 0 )) %>%
                                filter(year > 2005) %>%
                                group_by(grid) %>%
                                       summarise(tot = n(), ret2 = sum(ret, na.rm = T)) %>%
                                mutate(per = ret2/tot) 


library(viridis)


ggplot(retire_pos, aes(x = grid, y = per)) + geom_point() 


```



```{R}


retire <- all_data2 %>% filter(grid > 0) %>%
                            filter(year > 2005) %>%
                                mutate(ret = if_else(positionText == "R", 1, 0 )) %>%
                                mutate(less2 = if_else(grid < 2, 1,0), less3 = if_else(grid < 3,1,0))



```



```{r}


retiretot <- all_data2 %>% mutate(ret = if_else(positionText == "R", 1, 0 )) %>%
                            group_by(raceId) %>%
                              summarise( ret2 = sum(ret, na.rm = T))






````





```{r}


posg <- all_data2 %>% left_join(retiretot, by = "raceId") %>%
                  mutate(gridadj = grid - (Factor*ret2) ) %>%
                        mutate(xp =  gridadj - position) 




```


```{r}


gridadj1 <- posg %>% group_by(gridadj) %>%
                            summarise(meanp = mean(position, na.rm = T))

ggplot(gridadj, aes(x = gridadj, y = meanp)) + geom_point()

```

```{r}


lm1 <- lm( meanp ~ gridadj, gridadj1)





```


```{r}



driver <- posg %>% mutate(exp = predict(lm1, newdata = posg)) %>%
                   filter(year > 1995) %>%
                      mutate(delta = exp - position) %>%
                    group_by(driverRef) %>%
                        summarise(meanxp = mean(delta, na.rm= T), races = n()) 

ggplot(driver, aes(x = races, y = meanxp, label = driverRef)) + geom_text()





````






```{r}


ham <- posg %>% filter(code == "RAI") %>%
                    group_by(year) %>%
                        summarise(meanxp = mean(xp, na.rm= T), races = n()) 


ggplot(ham, aes(x = year, y = meanxp)) + geom_col()

```




```{r}



ham2 <- posg %>% mutate(exp = predict(lm1, newdata = posg)) %>%
                  filter(code == "HAM")  %>%
                     
                      filter(!is.na(delta))


ggplot(ham2, aes(x = raceno, y = delta)) + geom_line()


```



```{R}




R121 <- posg %>% mutate(exp = predict(lm1, newdata = posg)) %>%
                        filter(raceId == 1052) %>%
                               mutate(delta = exp - position)



```


```{r}


position <- c(1:24)

points <- c(175,155,138,122,107,93,80,68,57,47,38,30,23,17,12,8,5,3,2,0.8,0.4,0.2,0.1,0)


pointdat <- data.frame(position, points)


```

```{r}



maxavpos <- all_data2 %>% filter(grid > 0) %>%
                          group_by(year,  raceId, name.y) %>%
                              summarise(max = min(grid)) %>%
                                ungroup() %>%
                                  group_by(year, name.y) %>%
                                      summarise(meanp = mean(max, na.rm = T))





````
```{r}



qualbest <- qual %>% pivot_longer(cols = 7:9, names_to = "qaul", values_to = "times") %>%
                                      separate(times, into = c("m", "s","ms"), sep = ":")


qualbest$m <- as.numeric(as.character(qualbest$m))

qualbest$s <- as.numeric(as.character(qualbest$s))



qualbest2_m <- qualbest %>% mutate(qualt = m * 60 + s) %>%
                              group_by(raceId, driverId) %>%
                                slice_min(qualt) %>%
                                  ungroup() %>%
                      left_join(races, by = "raceId") %>%
                        left_join(constructors, by = "constructorId") %>%
                            group_by(raceId) %>%
                                slice_min(qualt) %>%
                                  select(raceId, qualt)

colnames(qualbest2_m)[2] <- "pole"


qualbest2<- qualbest %>% mutate(qualt = m * 60 + s) %>%
                      left_join(races, by = "raceId") %>%
                        left_join(constructors, by = "constructorId") %>%
                        left_join(qualbest2_m, by = "raceId") %>%
                          group_by(raceId, name.y) %>%
                            slice_min(qualt) %>%
                              mutate(qualdel = qualt / pole -1 ) %>%
                                select(raceId, name.y, qualt, pole, qualdel) %>%
                                    left_join(races, by = "raceId") %>%
                            group_by(year, name.y) %>%
                                  summarise(mean_del = mean(qualdel))
          


```
```{r}


totpoint <- all_data2 %>% filter(year > 1990) %>%
                            left_join(pointdat, by = "position") %>%
                              ungroup() %>%
                                filter(!is.na(points.y)) %>%
                              group_by(year, name.y) %>%
                                summarise(tp = sum(points.y, na.rm =T))
                                               

```


```{r}

point_co <- totpoint %>% left_join(qualbest2, by = c("name.y", "year")) %>%
                            left_join(maxavpos, by = c("name.y", "year"))


ggplot(point_co, aes(x = mean_del, y = tp)) + geom_point()


ggplot(point_co, aes(x = meanp, y = tp)) + geom_point()

````
```{r}





```


```{r}


all_data3 <- all_data2 %>% left_join(maxavpos, by = c("year", "constructorRef")) %>%
                              left_join(circuits, by = "circuitId") %>%
                               left_join(pointdat, by = "position") %>%
                                  left_join(retiretot, by = "raceId") %>%
                                  select(grid, position, year, status, points.y, meanp, ret2, Type) %>%
                                        filter(!is.na(position)) %>%
                                          filter(year > 1985) %>%
                                            filter(year < 2015) %>%
                                              select(grid, points.y, meanp, ret2, Type)



```



```{r}

split <- initial_split(all_data3, prop = 0.75)


train <- training(split)

testing <- testing(split)




```



```{r}


f1_rand <- 
                    rand_forest(mode = "regression") %>%
                      set_engine("ranger") %>%
                        fit(points.y ~ ., data = train)



```



```{r}


r1 <- all_data2 %>% left_join(maxavpos, by = c("year", "constructorRef")) %>%
                              left_join(circuits, by = "circuitId") %>%
                               left_join(pointdat, by = "position") %>%
                                  left_join(retiretot, by = "raceId") %>%
                                    filter(year == 2021) %>%
                                      mutate(grid2 = if_else(grid ==0, 20,grid)) %>%
                                        select(-grid) 

colnames(r1)[55] <- "grid"


predictions <- predict(f1_rand, new_data = r1)

```



```{r}


r1b <- r1 %>% bind_cols(predictions) %>%
                    select(grid, position, code, year, status, points.y, meanp, ret2, Type, .pred) 


```



```{r}

alldri <- all_data2 %>% left_join(maxavpos, by = c("year", "constructorRef")) %>%
                              left_join(circuits, by = "circuitId") %>%
                               left_join(pointdat, by = "position") %>%
                                  left_join(retiretot, by = "raceId") %>%
                                    filter(year > 2000) %>%
                                      filter(!is.na(position))



predictions <- predict(f1_rand, new_data = alldri)



````



```{r}


alldri2 <- alldri %>% bind_cols(predictions) %>%
                    select(grid, position, code, year, status, points.y, meanp, ret2, Type, .pred) %>%
                          mutate(delta = points.y - .pred) %>%
                            group_by(code) %>%
                              summarise(meap = mean(delta), n = n())


ggplot(alldri2, aes(x = n, y = meap, label = code)) + geom_text()




```

```{r}



alldri3 <- alldri %>% bind_cols(predictions) %>%
                    select(grid, position, code,raceno, year, status, points.y, meanp, ret2, Type, .pred) %>%
                          mutate(delta = points.y - .pred) %>%
                              filter(code == "VER")



ggplot(alldri3, aes(x = raceno, y = delta)) + geom_line()



````

```{r}


f1_folds <- bootstraps(train, strata = points.y)
f1_folds




```


```{r}

ranger_recipe <-
  recipe(formula =  points.y ~ ., data = train) 


ranger_spec <-
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>%
  set_mode("regression") %>%
  set_engine("ranger")

ranger_workflow <-
  workflow() %>%
  add_recipe(ranger_recipe) %>%
  add_model(ranger_spec)

set.seed(8577)
doParallel::registerDoParallel()
ranger_tune <-
  tune_grid(ranger_workflow,
    resamples = f1_folds,
    grid = 11
  )






```

```{r}

show_best(ranger_tune, metric = "rsq")




```



```{r}

autoplot(ranger_tune)


````



```{r}

f1_rand2 <- 
                    rand_forest(mode = "regression", mtry = 2, min_n = 32) %>%
                      set_engine("ranger") %>%
                        fit(points.y ~ ., data = train)








````


```{r}


predictions1 <- predict(f1_rand, new_data = r1)
predictions2 <- predict(f1_rand2, new_data = r1)

r1b <- r1 %>% bind_cols(predictions1) %>% 
                bind_cols(predictions2) %>% 
                    select(grid, raceId, position, code, year, status, points.y, meanp, ret2, Type,.pred...56,.pred...57 )




````

```{r}
 
r1c <- r1b %>% rename(mod1 = .pred...56, mod2=  .pred...57, actp = points.y) %>%
                              pivot_longer(cols = c("mod1", "mod2", "actp"), names_to = "meas", values_to = "val")



ggplot(r1c, aes(x = reorder(code, position), y = val, col = meas)) + geom_point() + coord_flip()






```

```{r}


predictions3 <- predict(f1_rand, new_data = alldri)

predictions4 <- predict(f1_rand2, new_data = alldri)



alldri4 <- alldri %>% bind_cols(predictions3) %>%
                       bind_cols(predictions4) %>%
                           filter(code == "NOR") %>%
               select(grid, position, code,raceno, year, status, points.y, meanp, ret2, Type ,.pred...56, .pred...57 ) %>%
                          rename(mod1 = .pred...56, mod2=  .pred...57, actp = points.y) %>%
                          mutate(delta1 = actp - mod1, delta2 = actp - mod2) %>%
                              select(raceno, delta1, delta2) %>%
                                  pivot_longer(cols = 2:3, names_to = "mod", values_to = "val")



ggplot(alldri4, aes(x = raceno, y = val, col= mod)) + geom_line()



```






```{r}


totp <-   r1b %>% group_by(code) %>%
                          summarise(tp = sum(points.y, na.rm = T), totexp = sum(.pred...56)) %>%
                              select(code,tp)


tttt <- r1b %>% group_by(code) %>%
                          summarise(totp = sum(points.y, na.rm = T), totexp = sum(.pred...56)) 


plot1 <- r1b %>% group_by(code) %>%
                          summarise(totp = sum(points.y, na.rm = T), totexp = sum(.pred...56)) %>%
                              pivot_longer(cols = 2:3, names_to = "meas", values_to = "val") %>%
                                      left_join(totp, by = "code") %>%
                                          left_join(tttt, by = "code") %>%
                                            mutate(delta = tp - totexp) %>%
                                              mutate(colca = if_else(delta < 0, "neg", "pos"))
                                                  
cols <- c("neg" = "#9800c7", "pos" = "#fac000")


ggplot(plot1, aes(x = reorder(code,tp), y = val)) + geom_point(aes(),size =5, col = "white") +
               geom_segment(aes(y = tp, yend = totexp, x = code, xend = code, col = colca), size = 3) +
                                                    coord_flip() +
                                              labs(x = "", y = "points", title = "Season 2021 Expected Points by Driver", subtitle = "Yellow Driver is performing above Expected, Purple below") +
                                    scale_colour_manual(values = cols) +
                                                        theme(panel.background = element_blank())


```